### ISSUE TITLE
请问自定义分词为什么不支持中文+数字？

### ISSUE THREAD

**Issue by leiguorui** [chenlb/mmseg4j-core#2]
比如，我想把”奥迪A1“做为一个词，写在了自定义词典里，分词之后，我期望的结果是“奥迪A1”，但是得到的是“奥迪|A1”

在IK的分词器里也是这样。

请问，我写在自定义词典里的词，如何分到一个词？

**Comment by chenlb** [comment]
mmseg4j 分词是先把连续中文的取出来分词。加自定义的非中文词无意义。这个功能要另一个产品“只按词库来挖词”

**Comment by leiguorui** [comment]
谢谢你的回复
