### ISSUE TITLE
letter and digit

### ISSUE THREAD

**Issue by roaporl** [chenlb/mmseg4j-core#3]
why default seg letter and digit together ? How can I set to split them ?
Maybe they should be splitted.

**Comment by chenlb** [comment]
make easy for [CutLetterDigitFilter](https://github.com/chenlb/mmseg4j-solr/blob/master/src/main/java/com/chenlb/mmseg4j/analysis/CutLetterDigitFilter.java)

letter and digit together to cut is easy for separate scene。but separate is first，head to join for letter and digit together  scene

**Comment by roaporl** [comment]
But I have used StopFilter in my stream increaseToken phase

**Comment by roaporl** [comment]
OK, thanks, I got it
